/** Labels for 28 observation inputs used in visualization */
export const OBS_LABELS = [
  "Position X",
  "Position Z",
  "Heading sin",
  "Heading cos",
  "HP (fraction)",
  "Weapon (type)",
  "Reload",
  "Enemy visible",
  "Distance to enemy",
  "Enemy angle sin",
  "Enemy angle cos",
  "Enemy HP",
  "Enemy weapon",
  "Weapon visible",
  "Weapon type",
  "Distance to weapon",
  "Weapon angle sin",
  "Weapon angle cos",
  "Ray: distance",
  "Ray: target type",
  "Wall 0°",
  "Wall 45°",
  "Wall 90°",
  "Wall 135°",
  "Wall 180°",
  "Wall 225°",
  "Wall 270°",
  "Wall 315°",
];

export const OUTPUT_LABELS = ["Forward", "Back", "Left", "Right", "Fire"];
